
---
- hosts: localhost
  gather_facts: no
  vars_prompt:
     - name: "ip_address"
       prompt: "\n Enter IP-Address "
       private: no
     - name: "vm_name"
       prompt: "\n Enter VM Name "
       private: no
  vars:
    vcenter_server: "172.16.130.65"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "Fri@co123!"
    datacenter_name: "FRISCO-DC"
    cluster_name: "Anthos-vSAN-Cluster"
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ vm_name }}"
      template: "{{ anthos-pre-jump }}"
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      resource_pool: "Ansible-VMs"
      datastore: "vsanDatastore"
      networks:
      - name: ANTHOS-VM-MANAGEMENT-PG
        ip: "{{ ip_address }}"
        netmask: 255.255.255.0
        gateway: 172.16.135.1
        type: static
        dns_servers: 8.8.8.8
      customization:
        hostname: "{{ vm_name }}"
        dns_servers:
        - 8.8.8.8
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost