---
- name: Get system users currently logged in
  hosts: all
  connection: local
  gather_facts: no
  roles:
   - juniper.junos
  tasks:
    - name: Retrieve facts from device running Junos OS
      juniper_junos_facts:
    - name: Print version
      debug:
        var: junos.fqdn
    - name: Run Junos Commands
      juniper_junos_command:
       commands="show security dynamic-vpn users"
       format=text
       dest=/home/ansible/{{ junos.fqdn }}.output
